# Generated by Django 5.0.6 on 2024-05-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joueur',
            name='type',
            field=models.CharField(choices=[('professionnel', 'Professionnel'), ('particulier', 'Particulier')], max_length=50),
        ),
    ]
