# Generated by Django 5.0.6 on 2024-05-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_joueur_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeu',
            name='annee_sortie',
            field=models.IntegerField(default=2000),
        ),
    ]
