# Generated by Django 5.0.6 on 2024-05-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_commentaire_date_commentaire_type_personne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='type_personne',
        ),
    ]
