# Generated by Django 5.0.6 on 2024-05-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_auteur_photos_alter_jeu_photo_boite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='note',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
